# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app_bundle.notification_topic_service:
        arguments: ['@doctrine.orm.entity_manager']
        class: AppBundle\Topic\NotificationTopic
        tags:
            - { name: gos_web_socket.topic }
    app_bundle.rpc_notification_service:
        arguments: ['@doctrine.orm.entity_manager']
        class: AppBundle\RPC\NotificationService
        tags:
            - { name: gos_web_socket.rpc }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
